# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "mootwoot"
description: > # this means to ignore newlines until "email:"
   Quiz and Moot

email: mootwootblr@gmail.com
#blog logo
logo: "http://i.imgur.com/WzuuUYi.jpg?1"
# blog cover
cover: "http://cdn.makeagif.com/media/4-16-2015/x14FDG.gif"
coverend: "http://cdn.makeagif.com/media/4-16-2015/x14FDG.gif"

name: 'mootwoot'
author: 'mootwoot'
author_image: "http://i.imgur.com/WzuuUYi.jpg?1"

kondi: "http://i.imgur.com/IbxM6Mq.jpg?1"
kondi_bio: Yenappa?

paginate:	5

url: "http://mootwoot.github.io/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
 # - icon:	twitter
#   url:	https://twitter.com/dirkfabisch
 #   desc: Follow me on twitter
  #  share_url: http://twitter.com/share
   # share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
 #   url:	https://github.com/dirkfabisch
  #  desc:	Fork me on github
   # share_url:
    #share_title:
    #share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
